### ISSUE TITLE
release: 2022.3.*, 2022.2.4

### ISSUE THREAD

**Issue by Pakisan** [asyncapi/jasyncapi-idea-plugin#13]
Hi @philCryoport, @nexoscp

I spent a few days figuring out how this should work and still have no idea. Tried several configurations with the same behavior - errors while plugin validation.

> If you develop a plugin, you can use new language features and APIs from Java 17, but only if the since-build attribute in plugin.xml is set to 223. If your plugin distribution needs to run on multiple versions of the IDE, for example, 2022.3 and 2022.2, then you must continue to use Java 11.

[reference](https://blog.jetbrains.com/platform/2022/08/intellij-project-migrates-to-java-17/)

So I decided to next:
- This https://github.com/asyncapi/jasyncapi-idea-plugin/pull/12 PR will be merged into 1.8.0 release branch and released
- Those https://github.com/asyncapi/jasyncapi-idea-plugin/pull/11, https://github.com/asyncapi/jasyncapi-idea-plugin/pull/8 PRs will be merged to 2.0.0 release branch and released.

My main thought is to split releases and bind them to JRE instead of IDEA' versions, to save functionality for our users who stay on older releases.

Because of this I also will remove meta information from version - +2021 and replace it with jre+{version} instead.

1.\*.\*+jre11 - for JRE 11
2.\*.\*+jre17 - for JRE 17

Any concerns? If none I will merge your PRs till 23.01 and build releases

**Comment by philCryoport** [comment]
> Because of this I also will remove meta information from version - +2021 and replace it with jre+{version} instead.
>
> `1.*.*+jre11` - for JRE 11
> `2.*.*+jre17` - for JRE 17

The only question I would ask is: given that versions are being built for particular IDEA versions, isn't it better to know which plugin version is built for which IDEA version?

In theory you could version-name based upon all three items:
<plugin version>+<IDEA version>+jre<JRE version>

**Comment by Pakisan** [comment]
> > Because of this I also will remove meta information from version - +2021 and replace it with jre+{version} instead.
> > `1.*.*+jre11` - for JRE 11
> > `2.*.*+jre17` - for JRE 17
> 
> The only question I would ask is: given that versions are being built for particular IDEA versions, isn't it better to know which plugin version is built for which IDEA version?
> 
> In theory you could version-name based upon all three items: `<plugin version>+<IDEA version>+jre<JRE version>`

I thought about it too and created compatibility table in release/1.8.0
