### ISSUE TITLE
[BUG] IntelliJ 2024.3 not supported

### ISSUE THREAD

**Issue by crussell52** [asyncapi/jasyncapi-idea-plugin#133]
### Describe the bug.

IntelliJ 2024.3 is not supported

### Expected behavior

IntelliJ 2024.3 is supported

### Screenshots

![image](https://github.com/user-attachments/assets/2a525365-48d7-40be-8261-27702566dde2)

### How to Reproduce

Run IntelliJ 2024.3 with plugin installed

### 🥦 Browser

None

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Pakisan** [comment]
published to:
- [JetBrains marketplace](https://plugins.jetbrains.com/plugin/15673-asyncapi/versions/stable/643480)
- [GitHub](https://github.com/asyncapi/jasyncapi-idea-plugin/releases/new?tag=2.7.0%2Bjre17)
