### ISSUE TITLE
New sub menu is not showing

### ISSUE THREAD

**Issue by Grinseteddy** [asyncapi/jasyncapi-idea-plugin#39]
#### Describe the bug
After installation of the plug in, the New context menu on a folder in the project structure is only shown if you hovering with your mouse over it. The sub menu on file is not shown at all.

#### How to Reproduce
1. Install Async plug in to intelliJ
2. Go to a folder in your project structure 
3. Call the context menu with the right mouse key
4. Only an empty gray rectangle is shown
5. Hovering with your mouse over it and the entries are shown
6. Select "File" - the according sub menu is not shown

#### Expected behavior
The file sub menu is shown. The entry "Async" is shown and can be selected to create a new file.

**Comment by Pakisan** [comment]
@Grinseteddy, hi!

Which version of IDEA do you use and with which theme?

**Comment by Pakisan** [comment]
I checked on 2023.2.4 (Ultimate Edition) with both ui - new and old

```
IntelliJ IDEA 2023.2.4 (Ultimate Edition)
Build #IU-232.10203.10, built on October 25, 2023
Runtime version: 17.0.8.1+7-b1000.32 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.6
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
    ide.experimental.ui=true

Non-Bundled Plugins:
    net.sf.opk.avro-schema-support (213.5.2)
    com.asyncapi.plugin.idea (2.3.0+jre17)
    com.intellij.spring.shell (232.8660.142)
    com.intellij.mermaid (0.0.14+IJ.232)
    Dart (232.9559.10)
    io.flutter (76.2.4)

Kotlin: 232-1.9.0-IJ10203.10
```


https://github.com/asyncapi/jasyncapi-idea-plugin/assets/3388414/b653e2ff-7720-4fbe-96b5-7f91be67da4d
https://github.com/asyncapi/jasyncapi-idea-plugin/assets/3388414/2625830d-d897-4310-b431-4c31c29eedac
https://github.com/asyncapi/jasyncapi-idea-plugin/assets/3388414/2f481c5e-51e6-46e3-aad8-40015721e984

**Comment by Pakisan** [comment]
Looks like this comments may be related:

> When I install the plug in, my IDE doesn't work as expected. The sub menu (New - file format) isn't opened anymore. I like the definition of event-driven APIs with Async API - but so it doesn't work. IntelliJ IDEA 2023.1.5 (Ultimate Edition)

https://plugins.jetbrains.com/plugin/15673-asyncapi/reviews#review=91710

> the plug-in block file->new

https://plugins.jetbrains.com/plugin/15673-asyncapi/reviews#review=91383

**Comment by Pakisan** [comment]
@Grinseteddy please check on your side - https://github.com/asyncapi/jasyncapi-idea-plugin/releases/tag/2.3.1%2Bjre17
