### ISSUE TITLE
Broken with newest version

### ISSUE THREAD

**Issue by Syndlex** [asyncapi/jasyncapi-idea-plugin#43]
#### Describe the bug

Plugin is broken in newest version of idea:
![grafik](https://github.com/asyncapi/jasyncapi-idea-plugin/assets/18503364/53853b96-ea63-4143-8034-470a7869fd5f)

**Comment by Pakisan** [comment]
> #### Describe the bug
> Plugin is broken in newest version of idea: ![grafik](https://private-user-images.githubusercontent.com/18503364/289882910-53853b96-ea63-4143-8034-470a7869fd5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MTMxMDcsIm5iZiI6MTcwMjQxMjgwNywicGF0aCI6Ii8xODUwMzM2NC8yODk4ODI5MTAtNTM4NTNiOTYtZWE2My00MTQzLTgwMzQtNDcwYTc4NjlmZDVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDIwMjY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxOWUzZmM1ZjQ1OTJlMzhkZjJjODk2MmNmZmNlZjI2MTQzNjFlZDAyOWMyNmRlMGFjNjg2ZmYxZjBhZmY1OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9kmwDq1rqVDNbPwZcyMy-4Kz7ak9gl3xBkz0RU3W0Vo)

@Syndlex waiting for review from JetBrains

**Comment by Pakisan** [comment]
@Syndlex new version was released

https://plugins.jetbrains.com/plugin/15673-asyncapi/versions/stable/454611
