### ISSUE TITLE
Is it possible that the plugin can handle $ref with external files?

### ISSUE THREAD

**Issue by hartmanjan1970** [asyncapi/jasyncapi-idea-plugin#48]
The plugin is not able to handle $ref with an external file.
if i have the following include file `MyPayloadThing.yml` 
```
      payload:
         $ref: "./schema/MyPayloadThing.yml"
```
The preview can not render the file, while the content is correct refering to the included file.

Is this a feature that could be added, would be very nice.
Thanks

**Comment by Pakisan** [comment]
@hartmanjan1970 Hi!

Can you show me your preview? I think that you are viewing your specification trough buggy IDEA preview, instead of my plugin

https://youtrack.jetbrains.com/issue/IDEA-331646/AsyncAPI-Preview-panel-cant-render-references-outside-given-specification

**Comment by hartmanjan1970** [comment]
I have no other preview than in the following screenshot (here is the include commented out)
![Screenshot from 2024-02-21 19-16-03](https://github.com/asyncapi/jasyncapi-idea-plugin/assets/23295800/a3f5b7b0-de34-4576-8144-60a75f0e418f)

Here screenshot with the include in intellij:
![Screenshot from 2024-02-21 19-17-00](https://github.com/asyncapi/jasyncapi-idea-plugin/assets/23295800/f6df96ee-e051-43c2-9642-9b03291dbc98)

**Comment by Pakisan** [comment]
> I have no other preview than in the following screenshot (here is the include commented out) ![Screenshot from 2024-02-21 19-16-03](https://private-user-images.githubusercontent.com/23295800/306730954-a3f5b7b0-de34-4576-8144-60a75f0e418f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NDAyNTYsIm5iZiI6MTcwODUzOTk1NiwicGF0aCI6Ii8yMzI5NTgwMC8zMDY3MzA5NTQtYTNmNWI3YjAtZGUzNC00NTc2LTgxNDQtNjBhNzVmMGU0MThmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDE4MjU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZTUwY2QzNjliZGNlMzZiYTc0MDFiZmFhMGVmYmEzYjU5YTc3ZWNmY2Q3MjVhMTY0MDg0NzJlOWQxYzkwZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.duWs21ztUUtW9-XdjPjfKfmTc3GmTfSXfoGemEOviNc)
> 
> Here screenshot with the include in intellij: ![Screenshot from 2024-02-21 19-17-00](https://private-user-images.githubusercontent.com/23295800/306730964-f6df96ee-e051-43c2-9642-9b03291dbc98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NDAyNTYsIm5iZiI6MTcwODUzOTk1NiwicGF0aCI6Ii8yMzI5NTgwMC8zMDY3MzA5NjQtZjZkZjk2ZWUtZTA1MS00M2MyLTk2NDItOWIwMzI5MWRiYzk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDE4MjU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MDMyMDRmNmUyNWFiZTRkNTdmOWU0Y2QwMjgwMmZhM2M3NTY3YjZmY2ZlNDJlOWIzZDNkNTBjMzUyNDA4YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d80ubndeezCa57HgVj536tUnGipJRM5NU3bfUkGLkjc)
> 
> In intellij i don't have any preview settings i can set for AsyncApi for as far i can find.

Yep, left one is preview introduced in 2023.2* and it's buggy

On a right top corner must be panel with preview inside idea, you must click it and receive same page, but with white theme

**Comment by Pakisan** [comment]
<img width="929" alt="image" src="https://github.com/asyncapi/jasyncapi-idea-plugin/assets/3388414/1b695632-41aa-473b-a4ba-4e6f5542889d">

**Comment by hartmanjan1970** [comment]
If i take a simple example i get a preview, but it goes to white before the editor preview gives up.
But apparently it is in my asyncapi defenition file.

**Comment by Pakisan** [comment]
> If i take a simple example i get a preview, but it goes to white when i add some stuff. And the build-in preview gives up before the editor preview gives up. 
> 
> But apparently it is in my asyncapi definition file.
> 
> 
> 
> mmm will check my asyncapi file.
> 
> Thanks
> 
> 

Will check it out. It may be bug in react component, which renders specification in preview 

You can check for errors in our studio

**Comment by theschles** [comment]
@hartmanjan1970 out of curiosity, did the above discussion help you?  Would it be ok if we close this issue?

**Comment by hartmanjan1970** [comment]
Yes, the discussion helped me with my definition of the AsyncApi contracts.
 thanks for the input gents

Now up to our next problem that is generation of Java code from the contract.... 
this is not yet successfull

**Comment by theschles** [comment]
Good luck to you with ironing out the Java code generation!  Closing this issue as there doesn't appear to be an issue with the plugin's code.

**Comment by Pakisan** [comment]
@hartmanjan1970 

fyi: https://github.com/asyncapi/jasyncapi-idea-plugin/issues/101

**Comment by Pakisan** [comment]
@hartmanjan1970  hi! New version is available
