### ISSUE TITLE
[BUG] Incompatible for WebStorm 2024.1 Build #WS-241.14494.235, built on March 27, 2024

### ISSUE THREAD

**Issue by korifey91** [asyncapi/jasyncapi-idea-plugin#53]
### Describe the bug.

Since Webstorm update to 2024.1 this plugin is incompatible

### Expected behavior

Expected that it is compatible

### Screenshots

![image](https://github.com/asyncapi/jasyncapi-idea-plugin/assets/40362351/529a9349-8c00-4ad5-8975-5959fb28709a)
![image](https://github.com/asyncapi/jasyncapi-idea-plugin/assets/40362351/0e31d4eb-4038-40bf-a777-90fb5f2b5845)

### How to Reproduce

1. Upgrade Webstorm to a new version (2024.1)

### 🥦 Browser

None

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Pakisan** [comment]
@korifey91 hi!

I'm waiting for approval from JetBrains. I think update will be available in few days

**Comment by korifey91** [comment]
Thank you, @Pakisan!

**Comment by Pakisan** [comment]
@korifey91 new version now available for downloading
