### ISSUE TITLE
[BUG] IntelliJ 2024.2 not supported

### ISSUE THREAD

**Issue by DennisHartrampf** [asyncapi/jasyncapi-idea-plugin#99]
### Describe the bug.

IntelliJ says that the latest version of the plugin 2.5.0+jre17 is not compatible with the latest IntelliJ version 2024.2.0.2.

#### Detailled version information:
IntelliJ IDEA 2024.2.0.2 (Ultimate Edition)
Build #IU-242.20224.419, built on August 19, 2024

### Expected behavior

The plugin is compatible with IntelliJ IDEA 2024.2.0.2 (Ultimate Edition).

### Screenshots

<img width="283" alt="Screenshot 2024-08-22 142039" src="https://github.com/user-attachments/assets/c58aacbf-90e1-4376-84d5-e2bc408d88b6">

### How to Reproduce

1. Install or update IntelliJ IntelliJ IDEA 2024.2.0.2 (Ultimate Edition)
2. Install plugin version 2.5.0+jre17
3. See that IntelliJ displays a warning and the plugin can't be used

### 🥦 Browser

None

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by philCryoport** [comment]
Confirmed @DennisHartrampf - thank you for catching that.

**Comment by DennisHartrampf** [comment]
You're welcome. I also tried working on it, but then was blocked by #102. After filing #102 I also saw that you already worked on this (#99) issue, so I think my part is done here 😄.
I'll just wait for a release. Thanks for your good work!
